export { identityRegistryAbi, reputationRegistryAbi } from './abis/index.js'
export {
  getErc8004Addresses,
  MAINNET_ADDRESSES,
  supportedChainIds,
  TESTNET_ADDRESSES,
} from './addresses.js'
export type {
  GetAgentWalletParameters,
  GetMetadataParameters,
  GetVersionParameters,
  IsRegisteredParameters,
  MetadataSetResult,
  RegisterAgentParameters,
  RegisterResult,
  ResolveAgentParameters,
  ResolvedAgent,
  SetAgentURIParameters,
  SetAgentWalletParameters,
  SetMetadataParameters,
  SignAgentWalletConsentParameters,
  UnsetAgentWalletParameters,
  URIUpdatedResult,
  VerifyAgentIdParameters,
} from './identity/index.js'
export {
  getAgentWallet,
  getMetadata,
  getVersion as getIdentityVersion,
  isRegistered,
  parseMetadataSetReceipt,
  parseRegisterReceipt,
  parseURIUpdatedReceipt,
  registerAgent,
  resolveAgent,
  setAgentURI,
  setAgentWallet,
  setMetadata,
  signAgentWalletConsent,
  unsetAgentWallet,
  verifyAgentId,
} from './identity/index.js'
export type {
  AppendResponseParameters,
  Feedback,
  FeedbackEntry,
  FeedbackRevokedResult,
  GetClientsParameters,
  GetIdentityRegistryParameters,
  GetLastIndexParameters,
  GetResponseCountParameters,
  GetSummaryParameters,
  GiveFeedbackParameters,
  GiveFeedbackResult,
  ReadAllFeedbackParameters,
  ReadFeedbackParameters,
  ReputationSummary,
  ResponseAppendedResult,
  RevokeFeedbackParameters,
} from './reputation/index.js'
export {
  appendResponse,
  getClients,
  getIdentityRegistry,
  getLastIndex,
  getResponseCount,
  getSummary,
  getVersion as getReputationVersion,
  giveFeedback,
  parseFeedbackRevokedReceipt,
  parseGiveFeedbackReceipt,
  parseResponseAppendedReceipt,
  readAllFeedback,
  readFeedback,
  revokeFeedback,
} from './reputation/index.js'
export type { Erc8004Addresses } from './types.js'
